# Связь с разработчиком:
# VK - @feymer31
# TG - @feymerwtf
commands: # Команды которые будут запрещены
  - "/ban"
  - "/mute"
  - "/kick"
messages:
  player-in-pvp: "&fВы не можете взаимодействовать с этим игроком, потому что он находится в режиме боя." # Сообщение, когда игрок в пвп
  reload: "&fВы перезагрузили плагин!" # Сообщение о перезагрузке плагина
  no-permission: "&fУ Вас недостаточно прав!" # Сообщение, когда у игрока недостаточно прав
  no-args: "&fНедостаточно аргументов!" # Сообщение, когда недостаточно аргументов