commands:
  - "/ban"
  - "/mute"
messages:
  player-in-pvp: "&fВы не можете взаимодействовать с этим игроком, потому что он находится в режиме боя."
  reload: "&fВы перезагрузили плагин!"
  no-permission: "&fУ Вас недостаточно прав!"
  no-args: "&fНедостаточно аргументов!"